spring.application.name=iot

spring.datasource.url=jdbc:sqlite:iot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core=DEBUG
spring.thymeleaf.check-template-location=false

logging.file.name=app.log
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.level.org.apache.coyote.http11=DEBUG
