spring.application.name=iot

spring.datasource.url=jdbc:sqlite:iot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core=DEBUG